packages:
  - apps/*
  - packages/*
catalog:
  '@daveyplate/better-auth-ui': 3.3.14
  '@icons-pack/react-simple-icons': ^13.8.0
  '@orpc/openapi': ^1.13.2
  '@orpc/server': ^1.13.2
  '@orpc/zod': ^1.13.2
  '@polar-sh/better-auth': ^1.6.3
  '@polar-sh/sdk': ^0.42.1
  '@refinedev/core': 5.0.8
  '@refinedev/react-hook-form': 5.0.3
  '@refinedev/react-table': 6.0.1
  '@tailwindcss/postcss': 4.1.18
  '@tailwindcss/typography': ^0.5.19
  '@tailwindcss/vite': ^4.1.18
  '@tanstack/react-form': 1.27.7
  '@tanstack/react-query': 5.90.16
  '@tanstack/react-query-devtools': 5.91.2
  '@tanstack/react-router': 1.147.3
  '@tanstack/react-router-devtools': 1.149.0
  '@tanstack/zod-adapter': 1.147.3
  '@trigger.dev/build': ^4.3.2
  '@trigger.dev/sdk': ^4.3.2
  '@types/eslint': ^8
  '@types/node': ^25.0.6
  '@types/react': ^19.2.8
  '@types/react-dom': ^19.2.3
  '@vitejs/plugin-react-swc': 4.2.2
  autoprefixer: ^10.4.23
  better-auth: 1.4.10
  clsx: 2.1.1
  deepmerge-ts: ^7.1.5
  dotenv: 17.2.3
  drizzle-kit: 0.31.8
  drizzle-orm: ^0.45.1
  drizzle-zod: ^0.8.3
  eslint: ^9.39.2
  hono: 4.11.3
  lucide-react: 0.562.0
  mediabunny: ^1.27.4
  next: ^16.1.1
  nitro: npm:nitro-nightly
  postcss: ^8.5.6
  prettier: ^3.7.4
  react: ^19.2.3
  react-dom: ^19.2.3
  react-icons: 5.5.0
  sonner: 2.0.7
  tailwind-merge: 3.4.0
  tailwindcss: ^4.1.18
  tailwindcss-animate: ^1.0.7
  turbo: ^2.7.4
  tw-animate-css: 1.4.0
  typescript: ^5.9.3
  vite: 7.3.1
  wrangler: 4.58.0
  zod: 4.3.5
catalogs:
  react18:
    '@tanstack/react-query': ^4.40.1
    '@types/react': ^18.3.11
    '@types/react-dom': ^18.3.1
    react: ^18.3.1
    react-dom: ^18.3.1
onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@clerk/shared'
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - better-sqlite3
  - core-js
  - esbuild
  - lefthook
  - protobufjs
  - sharp
  - workerd
