packages:
  - apps/*
  - packages/*

catalog:
  '@daveyplate/better-auth-ui': 3.2.11
  '@icons-pack/react-simple-icons': ^13.8.0
  '@orpc/openapi': ^1.11.3
  '@orpc/server': ^1.11.3
  '@orpc/zod': ^1.11.3
  '@polar-sh/better-auth': ^1.6.3
  '@polar-sh/sdk': ^0.31.0
  '@refinedev/core': 5.0.6
  '@refinedev/react-hook-form': 5.0.3
  '@refinedev/react-table': 6.0.1
  '@tailwindcss/postcss': 4.1.17
  '@tailwindcss/typography': ^0.5.19
  '@tailwindcss/vite': ^4.1.17
  '@tanstack/react-form': 1.25.0
  '@tanstack/react-query': 5.90.10
  '@tanstack/react-query-devtools': 5.90.2
  '@tanstack/react-router': 1.136.8
  '@tanstack/react-router-devtools': 1.136.8
  '@tanstack/zod-adapter': 1.136.8
  '@trigger.dev/build': ^4.1.0
  '@trigger.dev/sdk': ^4.1.0
  '@types/eslint': ^8
  '@types/node': ^24.10.1
  '@types/react': ^19.2.6
  '@types/react-dom': ^19.2.3
  '@vitejs/plugin-react-swc': 4.2.2
  autoprefixer: ^10.4.22
  better-auth: 1.4.1
  clsx: 2.1.1
  deepmerge-ts: ^7.1.5
  dotenv: 17.2.3
  drizzle-kit: 0.31.7
  drizzle-orm: ^0.44.7
  drizzle-zod: ^0.8.3
  eslint: ^9.39.1
  hono: 4.10.6
  lucide-react: 0.554.0
  mediabunny: ^1.25.0
  next: ^16.0.3
  nitro: npm:nitro-nightly
  postcss: ^8.5.6
  prettier: ^3.6.2
  react: ^19.2.0
  react-dom: ^19.2.0
  react-icons: 5.5.0
  sonner: 2.0.7
  tailwind-merge: 3.4.0
  tailwindcss: ^4.1.17
  tailwindcss-animate: ^1.0.7
  turbo: ^2.6.1
  tw-animate-css: 1.4.0
  typescript: ^5.9.3
  vite: 7.2.2
  wrangler: 4.49.0
  zod: 4.1.12

catalogs:
  react18:
    '@tanstack/react-query': ^4.40.1
    '@types/react': ^18.3.11
    '@types/react-dom': ^18.3.1
    react: ^18.3.1
    react-dom: ^18.3.1

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@clerk/shared'
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - better-sqlite3
  - core-js
  - esbuild
  - lefthook
  - protobufjs
  - sharp
  - workerd
